name: Update App Version

permissions:
  contents: write

on:
  push:
    branches: ["main"]

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Bump patch version
        run: |
          cd app
          npm version patch -m "Update version manifest to %s [skip ci]"

      - name: Update manifest.json
        run: |
          VERSION=$(node -p "require('./app/package.json').version")
          echo "{\"version\":\"$VERSION\"}" > app/static/manifest.json
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add app/static/manifest.json
          git commit -m "Sync manifest.json version to $VERSION [skip ci]" || echo "No changes"
          git push origin main --tags
