name: Update App Version

permissions:
  contents: write

on:
  push:
    branches: ["main"]

jobs:
  sync-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Read version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./app/package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update manifest.json
        run: |
          echo "{\"version\":\"${{ steps.get_version.outputs.version }}\"}" > app/static/manifest.json
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add app/static/manifest.json
          git diff --cached --quiet || git commit -m "Sync manifest.json version to ${{ steps.get_version.outputs.version }} [skip ci]"
          git push
